# Generated by Django 5.2.13 on 2026-04-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropScopeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', help_text='Name of this settings configuration', max_length=100, unique=True)),
                ('wsjtx_all_txt_path', models.CharField(blank=True, help_text='Path to WSJT-X ALL.TXT file', max_length=500)),
                ('wsjtx_poll_interval_seconds', models.IntegerField(default=30, help_text='How often to poll the WSJT-X file (in seconds)')),
                ('wsjtx_last_position', models.BigIntegerField(default=0, help_text='Last read position in the WSJT-X file')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this settings configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PropScope Settings',
                'verbose_name_plural': 'PropScope Settings',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
