# Generated by Django 5.2.13 on 2026-04-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_add_station_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this station profile (e.g., 'Home QTH', 'Portable Berg')", max_length=100)),
                ('callsign', models.CharField(blank=True, help_text='Station callsign (optional, can be empty for receive-only stations)', max_length=32)),
                ('locator', models.CharField(help_text="Maidenhead locator (4 or 6 characters, e.g., 'JN68')", max_length=6)),
                ('latitude', models.FloatField(blank=True, help_text='Station latitude (can be calculated from locator or manually set for precision)', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Station longitude (can be calculated from locator or manually set for precision)', null=True)),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Mark this profile as the default for distance calculations (only one should be default)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this profile is active (inactive profiles are kept for historical reference)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this station (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Station Profile',
                'verbose_name_plural': 'Station Profiles',
                'ordering': ['-is_default', '-is_active', 'name'],
                'indexes': [models.Index(fields=['is_default', 'is_active'], name='ui_stationp_is_defa_7c6d76_idx'), models.Index(fields=['locator'], name='ui_stationp_locator_eee57e_idx')],
            },
        ),
    ]
