# Generated by Django 5.2.13 on 2026-04-29 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeardSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When the signal was received')),
                ('frequency_mhz', models.FloatField(help_text='Frequency in MHz')),
                ('band', models.CharField(db_index=True, help_text='Band (e.g., 20m, 40m)', max_length=10)),
                ('mode', models.CharField(help_text='Mode (e.g., FT8, FT4)', max_length=20)),
                ('snr', models.IntegerField(help_text='Signal-to-noise ratio in dB')),
                ('dt', models.FloatField(help_text='Time offset in seconds')),
                ('audio_frequency', models.IntegerField(help_text='Audio frequency in Hz')),
                ('raw_message', models.CharField(help_text='Raw decoded message', max_length=100)),
                ('raw_line', models.TextField(help_text='Complete raw line from ALL.TXT')),
                ('callsign', models.CharField(db_index=True, help_text='Callsign', max_length=32)),
                ('callsign_country', models.CharField(blank=True, help_text='Country from callsign prefix', max_length=100, null=True)),
                ('callsign_continent', models.CharField(blank=True, help_text='Continent from callsign prefix', max_length=50, null=True)),
                ('qrz_url', models.URLField(blank=True, help_text='QRZ.com URL for the callsign', null=True)),
                ('locator', models.CharField(blank=True, db_index=True, help_text='Maidenhead locator (4 or 6 char)', max_length=6, null=True)),
                ('locator_lat', models.FloatField(blank=True, help_text='Latitude from locator', null=True)),
                ('locator_lon', models.FloatField(blank=True, help_text='Longitude from locator', null=True)),
                ('locator_country', models.CharField(blank=True, help_text='Country from locator', max_length=100, null=True)),
                ('locator_alt_country', models.CharField(blank=True, help_text='Alternative country from locator (for border areas)', max_length=100, null=True)),
                ('locator_continent', models.CharField(blank=True, help_text='Continent from locator', max_length=50, null=True)),
                ('locator_ambiguous', models.BooleanField(default=False, help_text='True if locator spans multiple countries')),
                ('distance_km', models.FloatField(blank=True, db_index=True, help_text='Distance in kilometers', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_run', models.ForeignKey(help_text='The import run this signal belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='heard_signals', to='ingest.importrun')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='cq_heardsig_timesta_9d9002_idx'), models.Index(fields=['callsign'], name='cq_heardsig_callsig_8ed245_idx'), models.Index(fields=['locator'], name='cq_heardsig_locator_d154a0_idx'), models.Index(fields=['band'], name='cq_heardsig_band_1f95a2_idx'), models.Index(fields=['distance_km'], name='cq_heardsig_distanc_03818b_idx'), models.Index(fields=['timestamp', 'band'], name='cq_heardsig_timesta_5e3dfa_idx'), models.Index(fields=['timestamp', 'callsign'], name='cq_heardsig_timesta_285bb7_idx')],
            },
        ),
    ]
