# Generated by Django 5.2.13 on 2026-04-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0003_banddefinition'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banddefinition',
            new_name='cq_banddefi_name_4a112d_idx',
            old_name='cq_banddefi_name_idx',
        ),
        migrations.RenameIndex(
            model_name='banddefinition',
            new_name='cq_banddefi_lower_f_56da94_idx',
            old_name='cq_banddefi_lower_f_idx',
        ),
        migrations.RenameIndex(
            model_name='banddefinition',
            new_name='cq_banddefi_is_acti_0bf7cb_idx',
            old_name='cq_banddefi_is_acti_idx',
        ),
        migrations.AddField(
            model_name='heardsignal',
            name='azimuth_deg',
            field=models.FloatField(blank=True, help_text='Azimuth/bearing from station to signal source in degrees (0-360)', null=True),
        ),
    ]
