# Generated by Django 5.2.13 on 2026-05-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0004_add_azimuth_deg'),
    ]

    operations = [
        migrations.AddField(
            model_name='heardsignal',
            name='cq_target',
            field=models.CharField(blank=True, db_index=True, help_text='CQ target prefix (e.g., DX, NA, EU)', max_length=10, null=True),
        ),
    ]
