# Generated by Django 5.2.14 on 2026-05-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0005_heardsignal_cq_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heardsignal',
            name='locator',
            field=models.CharField(blank=True, db_index=True, help_text='Maidenhead locator (4 or 6 char)', max_length=10, null=True),
        ),
    ]
