# Generated by Django 5.2.13 on 2026-04-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallsignPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, help_text='Callsign prefix (e.g., DL, G, K)', max_length=10, unique=True)),
                ('country', models.CharField(help_text='Country name', max_length=100)),
                ('continent', models.CharField(help_text='Continent code (e.g., EU, NA, AS)', max_length=50)),
                ('itu_region', models.IntegerField(blank=True, help_text='ITU region (1, 2, or 3)', null=True)),
                ('cq_zone', models.IntegerField(blank=True, help_text='CQ zone number', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
            ],
            options={
                'verbose_name': 'Callsign Prefix',
                'verbose_name_plural': 'Callsign Prefixes',
                'ordering': ['prefix'],
                'indexes': [models.Index(fields=['prefix'], name='callsign_ca_prefix_9345e9_idx'), models.Index(fields=['country'], name='callsign_ca_country_cce5fc_idx'), models.Index(fields=['continent'], name='callsign_ca_contine_f7c2a7_idx')],
            },
        ),
    ]
