# Generated by Django 5.2.13 on 2026-05-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callsign', '0002_add_fields_and_german_rules'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='callsignprefix',
            new_name='callsign_ca_is_acti_dc0ec6_idx',
            old_name='callsign_ca_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='germancallsignclassrule',
            new_name='callsign_ge_prefix__09c7cd_idx',
            old_name='callsign_ge_prefix__idx',
        ),
        migrations.RenameIndex(
            model_name='germancallsignclassrule',
            new_name='callsign_ge_is_acti_4e5812_idx',
            old_name='callsign_ge_is_acti_idx',
        ),
    ]
