# Generated by Django 5.2.13 on 2026-05-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsign', '0003_rename_callsign_ca_is_acti_idx_callsign_ca_is_acti_dc0ec6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(db_index=True, help_text='Normalized callsign (uppercase, no whitespace)', max_length=32, unique=True)),
                ('fixed_locator', models.CharField(help_text='Fixed Maidenhead locator for this station (e.g., JN58, PM95)', max_length=6)),
                ('fixed_latitude', models.FloatField(blank=True, help_text='Latitude calculated from fixed_locator', null=True)),
                ('fixed_longitude', models.FloatField(blank=True, help_text='Longitude calculated from fixed_locator', null=True)),
                ('country', models.CharField(blank=True, help_text='Country name (optional, can be auto-populated)', max_length=100)),
                ('continent', models.CharField(blank=True, help_text='Continent code (e.g., EU, NA, AS)', max_length=50)),
                ('source', models.CharField(default='manual', help_text='Source of information (e.g., manual, qrz, operator_page, log_observation)', max_length=50)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Whether this assignment has been verified')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this station should be used for enrichment')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this station')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Known Station',
                'verbose_name_plural': 'Known Stations',
                'ordering': ['callsign'],
                'indexes': [models.Index(fields=['callsign'], name='callsign_kn_callsig_9f9891_idx'), models.Index(fields=['country'], name='callsign_kn_country_8c4f4f_idx'), models.Index(fields=['continent'], name='callsign_kn_contine_6bbc90_idx'), models.Index(fields=['is_active'], name='callsign_kn_is_acti_0a33b8_idx'), models.Index(fields=['is_verified'], name='callsign_kn_is_veri_add5ab_idx')],
            },
        ),
    ]
