# Generated by Django 5.2.13 on 2026-04-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(help_text='Path to the imported file', max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the import started')),
                ('finished_at', models.DateTimeField(blank=True, help_text='When the import finished', null=True)),
                ('lines_total', models.IntegerField(default=0, help_text='Total lines in the file')),
                ('lines_imported', models.IntegerField(default=0, help_text='Successfully imported lines')),
                ('lines_skipped', models.IntegerField(default=0, help_text='Skipped lines')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or error messages')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='ingest_impo_started_5fe50a_idx'), models.Index(fields=['status'], name='ingest_impo_status_7d7e48_idx')],
            },
        ),
    ]
