# Generated by Django 5.2.13 on 2026-04-29 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this importer state (e.g., 'Default WSJT-X ALL.TXT', 'FT-710 Shack')", max_length=200)),
                ('log_file_path', models.CharField(help_text='Path to the monitored WSJT-X ALL.TXT file', max_length=500, unique=True)),
                ('last_position', models.BigIntegerField(default=0, help_text='Byte position in the file where last read ended')),
                ('last_size', models.BigIntegerField(blank=True, help_text='File size at last read (used to detect truncation or rotation)', null=True)),
                ('last_modified_at', models.DateTimeField(blank=True, help_text='Last known modification timestamp of the log file', null=True)),
                ('last_read_at', models.DateTimeField(blank=True, help_text='When the file was last successfully read', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message if import failed (empty if successful)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this importer state is active (inactive states are kept for historical reference)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_import_run', models.ForeignKey(blank=True, help_text='Reference to the most recent ImportRun (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importer_states', to='ingest.importrun')),
            ],
            options={
                'verbose_name': 'Importer State',
                'verbose_name_plural': 'Importer States',
                'ordering': ['-is_active', 'name'],
                'indexes': [models.Index(fields=['log_file_path'], name='ingest_impo_log_fil_64c2a0_idx'), models.Index(fields=['is_active'], name='ingest_impo_is_acti_7f261b_idx'), models.Index(fields=['-last_read_at'], name='ingest_impo_last_re_370933_idx')],
            },
        ),
    ]
