# Generated by Django 5.2.13 on 2026-04-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaidenheadArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locator', models.CharField(db_index=True, help_text='4-character Maidenhead locator (e.g., JN68)', max_length=4, unique=True)),
                ('center_lat', models.FloatField(help_text='Center latitude of the grid square')),
                ('center_lon', models.FloatField(help_text='Center longitude of the grid square')),
                ('primary_country', models.CharField(help_text='Primary country in this grid square', max_length=100)),
                ('alternative_countries', models.TextField(blank=True, help_text='Comma-separated list of alternative countries (for border areas)')),
                ('continent', models.CharField(help_text='Continent code (e.g., EU, NA, AS)', max_length=50)),
                ('is_ambiguous', models.BooleanField(default=False, help_text='True if this locator spans multiple countries')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
            ],
            options={
                'verbose_name': 'Maidenhead Area',
                'verbose_name_plural': 'Maidenhead Areas',
                'ordering': ['locator'],
                'indexes': [models.Index(fields=['locator'], name='geo_maidenh_locator_204798_idx'), models.Index(fields=['primary_country'], name='geo_maidenh_primary_57a102_idx'), models.Index(fields=['continent'], name='geo_maidenh_contine_3ad3d1_idx')],
            },
        ),
    ]
